spring.application.name=appusermanagement
spring.config.import=file:.env[.properties]
#spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

#spring.mvc.apiversion.use.header=API-Version

#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connectionTimeout=${CONN_TIMEOUT}
spring.datasource.hikari.maximumPoolSize=${POOL_MAXSIZE}

#Security Configuration
spring.security.user.name=${SEC_USERNAME}
spring.security.user.password=${SEC_PASSWORD}
logging.level.org.springframework.security=DEBUG

#JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}