spring.application.name=appusermanagement
#spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

#spring.mvc.apiversion.use.header=API-Version

spring.datasource.url=jdbc:postgresql://192.168.240.1:5432/app_dev_db
spring.datasource.username=postgres
spring.datasource.password=Gelbhund17
spring.datasource.hikari.connectionTimeout=2000
spring.datasource.hikari.maximumPoolSize=5
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration